# Generated by Django 5.1 on 2024-08-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('luces', models.BooleanField(default=False)),
                ('aire', models.BooleanField(default=False)),
                ('lucesauto', models.BooleanField(default=False)),
                ('aireauto', models.BooleanField(default=False)),
                ('tmmovON', models.IntegerField(help_text='Tiempo en segundos para encender luces al detectar movimiento')),
                ('tmmovOFF', models.IntegerField(help_text='Tiempo en segundos sin movimiento para apagar luces')),
                ('tempminima', models.FloatField(help_text='Temperatura mínima para encender aire acondicionado')),
                ('temppagar', models.FloatField(help_text='Temperatura máxima para apagar aire acondicionado')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.BooleanField()),
                ('tipodeact', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=10)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='controles.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='controles.tipo'),
        ),
    ]
