# Generated by Django 5.1 on 2024-08-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='urlcamara',
            field=models.CharField(default='', max_length=100),
        ),
    ]
