# Generated by Django 5.1 on 2024-08-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_configuracion_urlcamara'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='temperaturaact',
            field=models.FloatField(default=0, help_text='Temperatura actual'),
        ),
    ]
