# Generated by Django 5.1 on 2024-08-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0003_configuracion_temperaturaact'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='codoffair',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='codonair',
            field=models.CharField(default='', max_length=100),
        ),
    ]
