# Generated by Django 5.1 on 2024-08-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0004_configuracion_codoffair_configuracion_codonair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='codoffair',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='codonair',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
