# Generated by Django 5.1 on 2024-08-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0005_alter_configuracion_codoffair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='solcodoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='solcodon',
            field=models.BooleanField(default=False),
        ),
    ]
